version: '3.8'

services:
  api:
    image: agendero/api-agendero:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.agendaapi.rule=Host(`agendaapi.agendero.com`)
        - traefik.http.services.agendaapi.loadbalancer.server.port=3001
        - traefik.http.routers.agendaapi.service=agendaapi
        - traefik.http.routers.agendaapi.entrypoints=websecure
        - traefik.http.routers.agendaapi.tls.certresolver=letsencryptresolver
        - traefik.http.routers.agendaapi.tls=true
        - traefik.http.middlewares.agendaapi-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS
        - traefik.http.middlewares.agendaapi-cors.headers.accesscontrolallowheaders=*
        - traefik.http.middlewares.agendaapi-cors.headers.accesscontrolalloworiginlist=*
        - traefik.http.routers.agendaapi.middlewares=agendaapi-cors
    environment:
      # Database Configuration
      # Format: Host=your_host;Database=your_database;Username=your_username;Password=your_password
      - ConnectionStrings__PostgresConnection=Host=postgres_postgres;Database=agenda;Username=postgres;Password=your_password_here
      
      # API Key for Authentication
      # Generate a unique key for your installation
      - Authentication__ApiKey=your_api_key_here
      
      # License Key
      # Obtain from Agendero
      - LICENSE_KEY=your_license_key_here
      
      # Environment (production/development)
      - NODE_ENV=production
    volumes:
      - agendero_logs:/app/logs
    networks:
      - agendero-network

volumes:
  agendero_logs:
    name: agendero_logs

networks:
  agendero-network:
    external: true
